FROM ubuntu:precise

MAINTAINER Wouter Danes "https://github.com/wouterd"

RUN apt-get -y install python-software-properties
RUN add-apt-repository ppa:webupd8team/java
RUN apt-get update
RUN echo oracle-java7-installer shared/accepted-oracle-license-v1-1 select true | /usr/bin/debconf-set-selections

RUN apt-get -y install oracle-java7-installer
RUN update-alternatives --display java